### ISSUE TITLE
Do we crawl each category on sons.cz website?

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Crawler-config#1]
http://wayback.webarchiv.cz/secure/http://www.sons.cz/

There is array: dohledej_co_rozbalit containing parts of URL to harvest. Few works, few not. Check it out.

**Comment by JanMeritus** [comment]
podla pohladu na stranku a sposobu odkazovania je to mozno sposobene javascriptom, rsp sposobom odkazovania: 

`<a href="/sluzby" target="_top" alt="" title="" id="itemTextLink16" onclick="javascript:clickOnFolder(&quot;16&quot;)">Služby  </a>`

Nicmenenej zaradujem do testovacej sklizne

**Comment by horakjirinkp** [comment]
S odstupem času mohu prohlásit že zdroj se sklízí pravidelně a v požadované kvalitě.
