### ISSUE TITLE
nove zeny - záznamy s webarchivem

### ISSUE THREAD

**Issue by ghost** [WebArchivCZ/Crawler-config#10]
Zdravím,
v některých verzích máme místo originálního webu webarchiv, daly by se tyhle verze smazat prosím?

http://wayback.webarchiv.cz/secure/*/http://www.novezeny.eu
konkrétně 24. únor 2010 a 31. březen 2010

Děkuju

**Comment by horakjirinkp** [comment]
Bohužel ne.
Problém by měl zmizet po reindexace warců.
Web není na whitelistu, věřím že problém se vyřeší reindexací.
reindexace zatím plánována není.
