### ISSUE TITLE
nefunkční stav Vypovězená smlouva

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/Crawler-config#11]
zdroj http://konopijelek.cz má v Seederu (i v Adminu) statut "Vypovězená smlouva", ale přesto je vidět zvenčí online, což by neměl

**Comment by JanMeritus** [comment]
Ahoj, mame od neho:

konopijelek.cz
konopijelek.eu

Zakazat vsetko?

**Comment by mariehaskovcova** [comment]
jde jen o toto url http://konopijelek.cz

**Comment by JanMeritus** [comment]
Done

**Comment by JanMeritus** [comment]
este to nefrci

**Comment by JanMeritus** [comment]
Uz jop
