### ISSUE TITLE
Artmagazin www.artmagazin.eu se nesklízí

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Crawler-config#2]
```
-2 NOTCRAWLED https://www.artmagazin.eu/
301 CRAWLED http://artmagazin.eu/ https://www.artmagazin.eu/
```

**Comment by JanMeritus** [comment]
log z crawlu:

2017-05-16T11:31:48.394Z     1         54 dns:artmagazin.eu P http://artmagazin.eu/ text/dns #015 20170516113147777+27 sha1:VI5WUKXG3QOANBCWRQNLHMXNNI3RRFT3 http://artmagazin.eu/ -
2017-05-16T11:31:51.473Z   301        244 http://artmagazin.eu/robots.txt P http://artmagazin.eu/ text/html #015 20170516113151468+3 sha1:T7HILJ3RQ2AXPBVNJZYZLMZMM5ZH5PAL http://artmagazin.eu/ -
2017-05-16T11:31:51.485Z     1         55 dns:www.artmagazin.eu PRP https://www.artmagazin.eu/robots.txt text/dns #002 20170516113151481+3 sha1:PYNXQVY7YGTTAI6Y7GGZ6FYMHXTJXJSG http://artmagazin.eu/ -
2017-05-16T11:31:54.488Z   301        234 http://artmagazin.eu/ - - text/html #020 20170516113154483+3 sha1:ZP5AZJGBJ4WLTLKIRPPU4P25Z4OSX63X http://artmagazin.eu/ 3t
2017-05-16T11:31:54.732Z  -404          0 https://www.artmagazin.eu/robots.txt PR http://artmagazin.eu/robots.txt unknown #020 - - http://artmagazin.eu/ 2t
2017-05-16T11:31:57.543Z   301        245 http://artmagazin.eu/favicon.ico PI http://artmagazin.eu/robots.txt text/html #002 20170516113157538+3 sha1:5BAOUXDT3UVB7OONQVGXVGFEOM73WVS3 http://artmagazin.eu/ -
2017-05-16T17:33:48.428Z     1         55 dns:www.artmagazin.eu RP https://www.artmagazin.eu/ text/dns #119 20170516173348410+18 sha1:6UUAHJF6RVZ7MALDAMDDBXMAGZDSE5E4 http://artmagazin.eu/ -
2017-05-16T18:33:52.828Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #078 - - http://artmagazin.eu/ 30t
2017-05-16T23:33:57.663Z     1         55 dns:www.artmagazin.eu PIRP https://www.artmagazin.eu/favicon.ico text/dns #083 20170516233357658+4 sha1:FHYL6LLG73Z3WFJPLKHDN3XECDYUWV7A http://artmagazin.eu/ -
2017-05-17T01:34:02.515Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #100 - - http://artmagazin.eu/ 30t

**Comment by JanMeritus** [comment]
nonfatal-errors:

nonfatal-errors.log:2017-05-16T11:31:54.714Z  -404          0 https://www.artmagazin.eu/robots.txt PR http://artmagazin.eu/robots.txt unknown #020 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T11:31:54.938Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #020 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T11:47:06.917Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #198 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T12:02:10.575Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #004 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T12:17:33.521Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #068 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T12:33:03.033Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #073 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T12:48:07.883Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #153 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T13:03:08.948Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #023 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T13:18:30.770Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #107 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T13:33:37.607Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #176 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T13:48:38.007Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #080 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T14:03:40.283Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #033 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T14:18:45.253Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #165 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T14:33:45.549Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #131 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T14:48:45.819Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #075 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T15:03:46.151Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #193 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T15:18:46.354Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #125 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T15:33:46.511Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #198 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T15:48:46.745Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #009 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T16:03:46.896Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #129 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T16:18:47.351Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #075 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T16:33:47.672Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #071 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T16:48:47.918Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #075 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T17:03:48.141Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #054 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T17:18:48.356Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #013 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T17:33:51.639Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #104 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T17:48:51.866Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #154 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T18:03:52.016Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #104 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T18:18:52.625Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #097 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T18:33:52.828Z    -2          0 https://www.artmagazin.eu/ R http://artmagazin.eu/ unknown #078 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T18:33:52.976Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #078 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T18:48:53.274Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #085 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T19:03:53.441Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #102 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T19:18:53.645Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #121 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T19:33:53.840Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #167 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T19:48:54.000Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #186 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T20:03:54.318Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #134 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T20:18:54.588Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #079 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T20:33:54.759Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #138 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T20:48:55.012Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #066 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T21:03:55.182Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #183 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T21:18:55.464Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #082 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T21:33:55.630Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #184 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T21:48:56.002Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #128 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T22:03:56.208Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #156 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T22:18:56.500Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #027 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T22:33:56.880Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #082 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T22:48:57.125Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #027 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T23:03:57.322Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #082 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T23:18:57.525Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #083 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T23:34:00.814Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #083 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-16T23:49:01.027Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #126 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-17T00:04:01.191Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #025 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-17T00:19:01.360Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #101 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-17T00:34:01.636Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #132 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-17T00:49:01.815Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #055 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-17T01:04:02.082Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #046 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-17T01:19:02.341Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #091 - - http://artmagazin.eu/ -
nonfatal-errors.log:2017-05-17T01:34:02.515Z    -2          0 https://www.artmagazin.eu/favicon.ico PIR http://artmagazin.eu/favicon.ico unknown #100 - - http://artmagazin.eu/ -

**Comment by JanMeritus** [comment]
zaradeno do Testovaci sklizne

**Comment by ghost** [comment]
Kluci, 
psal mi vydavatel, že tam je ještě jeden rozdíl - v současnosti tam má místo http https...

tedy aktuálně stránka vypadá tahle: https://www.artmagazin.eu - dá se s tím něco dělat? je třeba to změnit ve wa adminu? 

Bo jestli správně koukám, tak ačkoliv se to ve waybacku tváří, že má v roce 2016 a 2017 fůru záznamů, tak mě to pořád odkazuje na tu starou z dubna 2016.

Díky

**Comment by kvasnicaj** [comment]
Dnes opět volal vydavatel, situace vypadá tak, že všechny verze, které byly vytvořeny po dubnu 2016 odkazují zpět právě na duben 2016. Zkusili jsme zadat explicitně semínko s https://, uvidíme jak to dopadne při prosincové sklizni. Stránka prošla v roce 2016 redesignem a nový design se zatím ani jednou nesklidil.

**Comment by horakjirinkp** [comment]
Problém vyřešil přechod na novější verzi crawleru.
