### ISSUE TITLE
journals.muni.cz - otestovat

### ISSUE THREAD

**Issue by ghost** [WebArchivCZ/Crawler-config#5]
pěkně prosím ASAP otestovat journals.muni.cz jestli je možné je sklízet - chtěli bychom je mít co nejdřív v archivu...

díky

**Comment by JanMeritus** [comment]
Stahnuto, treba oindexovat a pozriet logy.

Suvislost s :  #6

**Comment by JanMeritus** [comment]
Pridavam log: 

[errors2munipdf.txt](https://github.com/WebarchivCZ/Crawler-config/files/1022288/errors2munipdf.txt)

**Comment by JanMeritus** [comment]
Posobi, ze vacsina pdf sa stiahla fajn (kod 200), problemy posobi iba 

Kod 1

http://www.ped.muni.cz/wmus/studium/sborniky/youth_music_preferences_as_music_education_issues.pdf

A diplomka terezy bayerovej:

uri-errors.log:2017-05-16T19:07:18.712Z http://www.phil.muni.cz/wufv/home/studium/absolventske-prace "gnu.inet.encoding.IDNAException: Contains non-LDH characters. %20https" http:// https://is.muni.cz/th/326147/ff_m/Diplomova_prace_Tereza_Bajerova_final__1_.pdfero

Je vsak mozne, ze ide o suvislost s issue hlasenym Marii, co sa tyka casopisov ekf. Tj, ze crawler si to zaradi automaticky do surtov, nafari tomu 200 a frci dalej. Odporucam oindexovat a zistit co tam realne je a porovnat i so skliznou ekf. (docela rad by som to tuto stredu s Rudom dalej pozrel),

**Comment by westfood** [comment]
Vypadá to, že spousta těch časáků žije na vlastních doménách.. ale že by měli jít stáhnout - možná až na vyjímky..

a.) buď vyzobat URL domén časopisů a zadat je jako semínka
b.) nebo jen ty, co nejsou pod muni.cz např. testforum.cz a upravit scope, aby akceptovat vše z muni.cz
c.) udělat speciální sklizeň, která začne ja journals.muni.cz a sklidí prostě všechno..

**Comment by JanMeritus** [comment]
Podla mna by, pokial je to proveditelny, sme mali mat u dolezitych casopisu je ako a) +b) s povolenym jednym hop offom, obzvlast ked sa vedu ako casopisy co zbierame v seedri, alebo alephu.

**Comment by JanMeritus** [comment]
zaradene do testovaci sklizne

**Comment by horakjirinkp** [comment]
S odstupem času mohu prohlásit že zdroj se sklízí pravidelně a v požadované kvalitě.
