### ISSUE TITLE
periodika – sklízení pdf souborů

### ISSUE THREAD

**Issue by mariehaskovcova** [WebArchivCZ/Crawler-config#6]
příklady periodik, u kterých se nesklidily soubory v pdf (tzn. čísla časopisu), viz upozornění od Petry Šťastné z odděl. periodik

**European Review of Social Sciences**
http://erss2.webnode.cz/
http://wayback.webarchiv.cz/secure/20161031140201/http://erss2.webnode.cz/
  
**Právo, informace, bezpečnost : PBI**
http://www.teorieib.cz/pbi/
http://aleph.nkp.cz/F/?func=direct&doc_number=002611299&local_base=nkc
 
**Envigogika**
http://envigogika.cuni.cz 
http://wayback.webarchiv.cz/wayback/envigogika.cuni.cz (archivní verze stránek)

**Comment by JanMeritus** [comment]
Muzu buducit tyzden pustit sklizen len s tymito adresami a uvidime co nam to sklidi a hodi do errorov.  Nasimi beznymi nastavenimi to asi nebude.

**Comment by Bilinova** [comment]
u zdroje Právo do škol http://wayback.webarchiv.cz/wayback/http://www.pravodoskol.cz se nesklidily pdf soubory

**Comment by JanMeritus** [comment]
Seminka 

`http://erss2.webnode.cz/
http://www.teorieib.cz/pbi/
http://envigogika.cuni.cz
http://www.pravodoskol.cz
`
zaradene do testovaci sklizne

**Comment by mariehaskovcova** [comment]
další url adresa časopisu, u kterého nemáme sklizená pdfka - http://ielonline.eu/, časopis už je v tuto chvíli na nové adrese (http://www.ieletters.cz)

**Comment by mariehaskovcova** [comment]
další weby periodik, u kterých nejsou sklizena pdf: http://cm.osu.cz a http://www.ekf.vsb.cz/cerei/

**Comment by mariehaskovcova** [comment]
při QA jsem narazila na další zdroj, kde se nesklízí pdfka - http://www.biostatisticka.cz, konkrétně sekce výuka: https://wayback.webarchiv.cz/secure/20170425161223/http://www.biostatisticka.cz/vyuka/

první dvě pdf (lekce1,2) jsou sklizeny, další už ne

**Comment by mariehaskovcova** [comment]
další zdroj (QA), kde se nesklízí pdf - http://www.cgf.cz, část Dokumenty, https://wayback.webarchiv.cz/secure/20170426084117/http://cgf.cz/DocumentFolderDetail.aspx?IDMenu=35301121&IDDocumentFolder=47533

**Comment by horakjirinkp** [comment]
S odstupem času mohu prohlásit že níže uvedené zdroje své pdf soubory mají, a sklízí se pravidelně a v požadované kvalitě.
