### ISSUE TITLE
Vypadá, že se nesklízí: https://journals.muni.cz/cepsr/

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Crawler-config#7]
Podívat se do reportů ze sklizní a projít logy

**Comment by JanMeritus** [comment]
zaradene do testovaci sklizne

**Comment by horakjirinkp** [comment]
S odstupem času mohu prohlásit že od vyšší verze crawleru se zdroj sklízí pravidelně a v požadované kvalitě.
