### ISSUE TITLE
Vypadá, že se nesklízí:  http://journals.muni.cz/pedor/ 

### ISSUE THREAD

**Issue by westfood** [WebArchivCZ/Crawler-config#8]
Projít reporty a logy

**Comment by JanMeritus** [comment]
Ahoj, vskutku: 

len je to http"s":

-2 NOTCRAWLED, tj.  - HTTP connection to site failed

20170425094206/reports/seeds-report.txt:-2 NOTCRAWLED https://journals.muni.cz/pedor/
20170425094206/reports/source-report.txt:https://journals.muni.cz/pedor/ dns: 1

pokusil sa tam dostat viackrat znova s -2:

20170425094206/logs/nonfatal-errors.log:2017-04-26T19:13:23.568Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #102 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T19:28:56.823Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #085 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T19:44:29.137Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #047 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T19:59:51.553Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #111 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T20:15:08.114Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #141 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T20:30:32.954Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #125 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T20:45:56.243Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #152 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T21:01:09.964Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #175 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T21:16:13.300Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #076 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T21:31:25.739Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #153 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T21:46:47.362Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #018 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T22:02:13.556Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #097 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T22:18:06.192Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #143 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T22:33:44.252Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #181 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T22:49:38.670Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #085 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T23:05:00.478Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #151 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T23:20:30.990Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #113 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T23:35:56.739Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #045 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-26T23:51:21.551Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #081 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-27T00:06:44.541Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #063 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-27T00:21:59.757Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #002 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-27T00:37:09.532Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #107 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-27T00:52:29.426Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #105 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-27T01:07:49.713Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #076 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-27T01:23:13.735Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #095 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-27T01:38:59.882Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #127 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-27T01:54:14.692Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #010 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-27T02:09:17.029Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #067 - - https://journals.muni.cz/pedor/ -
20170425094206/logs/nonfatal-errors.log:2017-04-27T02:24:26.951Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #147 - - https://journals.muni.cz/pedor/ -

... je to dlhe, dal som vycucnut subora

V crawl.log:

20170425094206/logs/crawl.log:2017-04-26T23:51:00.968Z     1         57 dns:journals.muni.cz P https://journals.muni.cz/pedor/ text/dns #021 20170426235100944+17 sha1:VTODM7K6PRSJNFGMUX25VWGGQPCUBV3S https://journals.muni.cz/pedor/ -
20170425094206/logs/crawl.log:2017-04-27T02:24:26.963Z    -2          0 https://journals.muni.cz/pedor/ - - unknown #147 - - https://journals.muni.cz/pedor/ 30t
20170425094206/logs/crawl.log:2017-04-28T12:38:48.851Z     1         57 dns:journals.muni.cz LRLLLLLRP https://journals.muni.cz/pedor/issue/view/110 text/dns #043 20170428123848838+13 sha1:HNTQCZ4YEX3B7EYVGQ4ECASJNHEBKQGM http://kdf.mff.cuni.cz/ -
20170425094206/logs/crawl.log:2017-04-28T15:36:36.189Z    -2          0 https://journals.muni.cz/pedor/issue/view/110 LRLLLLLR http://www.ped.muni.cz/pedor/index.php?option=com_content&view=article&id=145&Itemid=139 unknown #004 - - http://kdf.mff.cuni.cz/ 30t
20170425094206/logs/crawl.log:2017-04-28T18:47:47.525Z     1         57 dns:journals.muni.cz LRLLLLLRP https://journals.muni.cz/pedor/issue/view/108 text/dns #062 20170428184747230+5 sha1:WQ5T2WUMV6ZTRVXRMEXZXOSL2MPNCOPG http://kdf.mff.cuni.cz/ -
20170425094206/logs/crawl.log:2017-04-28T23:03:40.940Z    -2          0 https://journals.muni.cz/pedor/issue/view/108 LRLLLLLR http://www.ped.muni.cz/pedor/index.php?option=com_content&view=article&id=147&Itemid=142 unknown #102 - - http://kdf.mff.cuni.cz/ 30t
20170425094206/logs/crawl.log:2017-04-30T01:42:16.320Z     1         57 dns:journals.muni.cz LLRP https://journals.muni.cz/pedor/issue/view/59 text/dns #059 20170430014216300+2 sha1:EFCRFV6OUAFPTSFHVW3BCFYGVSMSINN5 http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-04-30T06:00:46.324Z  -404          0 https://journals.muni.cz/robots.txt LLRP https://journals.muni.cz/pedor/issue/view/59 unknown #050 - - http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-04-30T07:44:40.780Z     1         57 dns:journals.muni.cz LLRP https://journals.muni.cz/pedor/issue/view/59 text/dns #055 20170430074440764+2 sha1:UQINFQWCIOUGICSXBHKPIOQTURC4SJIZ http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-04-30T08:03:37.226Z    -2          0 https://journals.muni.cz/pedor/issue/view/59 LLR http://www.ped.muni.cz/pedor/index.php?option=com_content&view=article&id=210&Itemid=187 unknown #042 - - http://www.ucitelske-listy.cz/ 30t
20170425094206/logs/crawl.log:2017-04-30T13:58:35.629Z     1         57 dns:journals.muni.cz LLRP https://journals.muni.cz/pedor/issue/view/100 text/dns #071 20170430135835621+1 sha1:Y66X4OWMMDPTPNTKER4NJCSGWQ3DP2AP http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-04-30T15:59:15.022Z    -2          0 https://journals.muni.cz/pedor/issue/view/100 LLR http://www.ped.muni.cz/pedor/index.php?option=com_content&view=article&id=187&Itemid=172 unknown #173 - - http://www.ucitelske-listy.cz/ 30t
20170425094206/logs/crawl.log:2017-04-30T20:11:51.303Z     1         57 dns:journals.muni.cz LLRP https://journals.muni.cz/pedor/issue/view/129 text/dns #151 20170430201151296+2 sha1:C4NX576ZTXJZNTTSPY4FOQIDBSJM5JLW http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-04-30T23:52:42.387Z    -2          0 https://journals.muni.cz/pedor/issue/view/129 LLR http://www.ped.muni.cz/pedor/index.php?option=com_content&view=article&id=179&Itemid=169 unknown #052 - - http://www.ucitelske-listy.cz/ 30t
20170425094206/logs/crawl.log:2017-05-01T02:23:03.925Z     1         57 dns:journals.muni.cz LLRP https://journals.muni.cz/pedor/issue/view/101 text/dns #027 20170501022303911+2 sha1:RQUL72GWSB63PZ7JNSMEGWDBEC7WDEUC http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-01T06:08:59.919Z  -404          0 https://journals.muni.cz/robots.txt LLRP https://journals.muni.cz/pedor/issue/view/101 unknown #065 - - http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-01T07:39:56.538Z    -2          0 https://journals.muni.cz/pedor/issue/view/101 LLR http://www.ped.muni.cz/pedor/index.php?option=com_content&view=article&id=177&Itemid=167 unknown #024 - - http://www.ucitelske-listy.cz/ 30t
20170425094206/logs/crawl.log:2017-05-01T08:32:09.361Z     1         57 dns:journals.muni.cz LLRP https://journals.muni.cz/pedor/issue/view/103 text/dns #066 20170501083209355+5 sha1:UDA2OIYR4OKK6EQEM3JXBP2ZJ7KELIER http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-01T14:39:04.753Z     1         57 dns:journals.muni.cz LLRP https://journals.muni.cz/pedor/issue/view/103 text/dns #188 20170501143904688+2 sha1:YTPE26VKFI5FWJ2SYANPULEA4IZE4XNE http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-01T15:10:29.403Z    -2          0 https://journals.muni.cz/pedor/issue/view/103 LLR http://www.ped.muni.cz/pedor/index.php?option=com_content&view=article&id=165&Itemid=163 unknown #031 - - http://www.ucitelske-listy.cz/ 30t
20170425094206/logs/crawl.log:2017-05-01T20:52:13.964Z     1         57 dns:journals.muni.cz LLRP https://journals.muni.cz/pedor/issue/view/105 text/dns #097 20170501205213945+3 sha1:TO4TQZP5KIBU6U27K54WHRE2NR5RGUJX http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-01T22:27:12.844Z    -2          0 https://journals.muni.cz/pedor/issue/view/105 LLR http://www.ped.muni.cz/pedor/index.php?option=com_content&view=article&id=162&Itemid=161 unknown #068 - - http://www.ucitelske-listy.cz/ 30t
20170425094206/logs/crawl.log:2017-05-02T03:07:09.208Z     1         57 dns:journals.muni.cz LLRP https://journals.muni.cz/pedor/issue/view/133 text/dns #048 20170502030709205+2 sha1:EWRVY7UVFQGNLDBMHHWQFGOYCURCDHVC http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-02T05:42:37.205Z    -2          0 https://journals.muni.cz/pedor/issue/view/133 LLR http://www.ped.muni.cz/pedor/index.php?option=com_content&view=article&id=153&Itemid=144 unknown #187 - - http://www.ucitelske-listy.cz/ 30t
20170425094206/logs/crawl.log:2017-05-02T15:27:11.293Z     1         57 dns:journals.muni.cz LLLP https://journals.muni.cz/pedor/article/view/3707/pdf_federicova text/dns #006 20170502152711271+2 sha1:E5AD7Y22HRHXQW36YXGHLIBQRBQKJKU5 http://www.ceskaskola.cz/ -
20170425094206/logs/crawl.log:2017-05-02T16:27:46.849Z    -2          0 https://journals.muni.cz/pedor/article/view/3707/pdf_federicova LLL http://www.ceskaskola.cz/2015/09/miroslava-federicova-daniel-munich.html unknown #092 - - http://www.ceskaskola.cz/ 30t
20170425094206/logs/crawl.log:2017-05-03T03:43:12.301Z     1         57 dns:journals.muni.cz LLLP https://journals.muni.cz/pedor/article/view/4384/pdf7 text/dns #051 20170503034312287+3 sha1:XK5WR2Z3GXAZ4LBLPB6VO4ZL32XKLCPQ http://www.ceskaskola.cz/ -
20170425094206/logs/crawl.log:2017-05-03T06:17:00.955Z  -404          0 https://journals.muni.cz/robots.txt LLLP https://journals.muni.cz/pedor/article/view/4384/pdf7 unknown #041 - - http://www.ceskaskola.cz/ -
20170425094206/logs/crawl.log:2017-05-03T06:32:53.654Z    -2          0 https://journals.muni.cz/pedor/article/view/4384/pdf7 LLL http://www.ceskaskola.cz/2015/12/tomas-janik-skola-na-kruhovem-objezdu.html unknown #182 - - http://www.ceskaskola.cz/ 30t
20170425094206/logs/crawl.log:2017-05-03T09:52:16.228Z     1         57 dns:journals.muni.cz LLLP https://journals.muni.cz/pedor/article/view/3709/pdf_stech text/dns #061 20170503095216207+3 sha1:G2HLMVOPPZD5ZWDLFP5B3HTAXPF65ZG7 http://www.ceskaskola.cz/ -
20170425094206/logs/crawl.log:2017-05-03T13:43:47.026Z    -2          0 https://journals.muni.cz/pedor/article/view/3709/pdf_stech LLL http://www.ceskaskola.cz/2016/12/stanislav-stech-srovnavaci.html unknown #130 - - http://www.ceskaskola.cz/ 30t
20170425094206/logs/crawl.log:2017-05-03T16:01:16.358Z     1         57 dns:journals.muni.cz LLLP https://journals.muni.cz/pedor/issue/view/60 text/dns #127 20170503160116355+2 sha1:R3BUYNJC5NKYJGEL4EP67TA7QD7WLJMA http://www.ceskaskola.cz/ -
20170425094206/logs/crawl.log:2017-05-03T20:52:47.503Z    -2          0 https://journals.muni.cz/pedor/issue/view/60 LLL http://www.ceskaskola.cz/2016/04/tomas-janik-vladimira-spilkova-michaela.html unknown #008 - - http://www.ceskaskola.cz/ 30t
20170425094206/logs/crawl.log:2017-05-05T10:54:42.310Z     1         57 dns:journals.muni.cz LLLP https://journals.muni.cz/pedor/article/view/5227 text/dns #125 20170505105442289+2 sha1:C4BJOXRKIYCVXD2EEKNUNTW3GENWIYJM http://www.ceskaskola.cz/ -
20170425094206/logs/crawl.log:2017-05-05T15:00:45.972Z    -2          0 https://journals.muni.cz/pedor/article/view/5227 LLL http://www.ceskaskola.cz/2016/04/jiri-mares-skolni-psycholog-jako.html unknown #039 - - http://www.ceskaskola.cz/ 30t
20170425094206/logs/crawl.log:2017-05-05T23:12:02.334Z     1         57 dns:journals.muni.cz LLLLLP https://journals.muni.cz/pedor/index text/dns #160 20170505231202330+3 sha1:6ML5SEPQKARWA6KSB62DTKPXAPDMXRU5 http://ulug.ff.cuni.cz/ -
20170425094206/logs/crawl.log:2017-05-06T05:19:56.899Z   -50          - https://journals.muni.cz/pedor/index LLLLL http://www.ujc.cas.cz/zakladni-informace/pracovnici/kaderka-petr.html unknown #155 - - http://ulug.ff.cuni.cz/ 30t
20170425094206/logs/crawl.log:2017-05-06T05:19:57.483Z     1         57 dns:journals.muni.cz LLLLLP https://journals.muni.cz/pedor/index text/dns #053 20170506051957457+4 sha1:B4PPLJOU642NTXA6R62V3M7AS2DRDNMU http://ulug.ff.cuni.cz/ -
20170425094206/logs/crawl.log:2017-05-06T17:37:40.975Z     1         57 dns:journals.muni.cz LLP https://journals.muni.cz/pedor/article/view/5457/4556 text/dns #098 20170506173740972+3 sha1:JARKJSSDSXGP72QBV6GOJFJK26CF77UP http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-06T19:24:59.184Z    -2          0 https://journals.muni.cz/pedor/article/view/5457/4556 LL http://www.ucitelske-listy.cz/search/label/v%C3%BDzkum%20a%20hodnocen%C3%AD unknown #023 - - http://www.ucitelske-listy.cz/ 30t
20170425094206/logs/crawl.log:2017-05-07T12:03:00.266Z     1         57 dns:journals.muni.cz LLLP https://journals.muni.cz/pedor/issue/archive text/dns #055 20170507120300262+3 sha1:DTK447YANCT7TATWRADGCK7FQQND4TQR http://knihovna.jinonice.cuni.cz/ -
20170425094206/logs/crawl.log:2017-05-07T16:38:52.565Z    -2          0 https://journals.muni.cz/pedor/issue/archive LLL http://knihovna.jinonice.cuni.cz/aktualne-odebirane-casopisy unknown #009 - - http://knihovna.jinonice.cuni.cz/ 30t
20170425094206/logs/crawl.log:2017-05-09T00:53:25.064Z     1         57 dns:journals.muni.cz LLP https://journals.muni.cz/pedor/article/view/830 text/dns #150 20170509005325044+3 sha1:6AREUD2XJCGOBEH6RXEM2ISYCE4IECP7 http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-09T04:13:24.950Z    -2          0 https://journals.muni.cz/pedor/article/view/830 LL http://www.ucitelske-listy.cz/2016/03/ unknown #001 - - http://www.ucitelske-listy.cz/ 30t
20170425094206/logs/crawl.log:2017-05-09T06:47:17.007Z  -404          0 https://journals.muni.cz/robots.txt LLP https://journals.muni.cz/pedor/article/view/1108 unknown #093 - - http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-09T07:03:01.527Z     1         57 dns:journals.muni.cz LLP https://journals.muni.cz/pedor/article/view/1108 text/dns #145 20170509070301523+2 sha1:LKG5Q2UPOHTXXZVM5DO6RU3DPYIUYVOP http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-09T11:05:20.598Z    -2          0 https://journals.muni.cz/pedor/article/view/1108 LL http://www.ucitelske-listy.cz/2016/03/ unknown #154 - - http://www.ucitelske-listy.cz/ 30t
20170425094206/logs/crawl.log:2017-05-09T19:05:44.785Z     1         57 dns:journals.muni.cz LLP https://journals.muni.cz/pedor/article/viewFile/4380/pdf2 text/dns #167 20170509190544760+3 sha1:2QLUIZ2IJPLU7PBVMFZAHZH5QN2PBYJM http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-10T01:05:57.974Z   -50          - https://journals.muni.cz/pedor/article/viewFile/4380/pdf2 LL http://www.ucitelske-listy.cz/2016_03_08_archive.html unknown #035 - - http://www.ucitelske-listy.cz/ 30t
20170425094206/logs/crawl.log:2017-05-10T01:05:57.994Z     1         57 dns:journals.muni.cz LLP https://journals.muni.cz/pedor/article/viewFile/4380/pdf2 text/dns #035 20170510010557974+3 sha1:E3GAOWRHBCGF3POQ3FJ7YRJKPIJMTOXS http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-11T13:23:36.037Z     1         57 dns:journals.muni.cz LLP https://journals.muni.cz/pedor/article/view/2984/pdf_10 text/dns #122 20170511132336027+3 sha1:NQD57WU2QU5XSPONJY2XFCJSAMQDJJFW http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-11T18:56:12.634Z    -2          0 https://journals.muni.cz/pedor/article/view/2984/pdf_10 LL http://www.ucitelske-listy.cz/2015/03/ unknown #097 - - http://www.ucitelske-listy.cz/ 30t
20170425094206/logs/crawl.log:2017-05-11T19:26:22.581Z     1         57 dns:journals.muni.cz LLP https://journals.muni.cz/pedor/article/viewFile/2984/pdf_10 text/dns #194 20170511192622555+3 sha1:U6X2XQSXHHYCE7OQAQROBEBIMN57ZHWV http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-12T01:29:10.982Z     1         57 dns:journals.muni.cz LLP https://journals.muni.cz/pedor/article/viewFile/2984/pdf_10 text/dns #146 20170512012910978+3 sha1:4GX2P3R43EGA4J3Z3UQV3NG6NCY266T3 http://www.ucitelske-listy.cz/ -
20170425094206/logs/crawl.log:2017-05-12T01:44:14.358Z    -2          0 https://journals.muni.cz/pedor/article/viewFile/2984/pdf_10 LL http://www.ucitelske-listy.cz/2015/03/ unknown #001 - - http://www.ucitelske-listy.cz/ 30t
20170425094206/logs/crawl.log:2017-05-12T07:17:01.286Z  -404          0 https://journals.muni.cz/robots.txt RLLLP https://journals.muni.cz/pedor/article/viewFile/621/600 unknown #009 - - http://ascestinaru.cz/ -
20170425094206/logs/crawl.log:2017-05-12T07:32:05.175Z     1         57 dns:journals.muni.cz RLLLP https://journals.muni.cz/pedor/article/viewFile/621/600 text/dns #098 20170512073205172+2 sha1:4EXP5B5XEDVLAADEWZL7ATZ6TXLW6L3U http://ascestinaru.cz/ -
20170425094206/logs/crawl.log:2017-05-12T08:33:03.430Z    -2          0 https://journals.muni.cz/pedor/article/viewFile/621/600 RLLL http://www.ascestinaru.cz/tomas-janik-vladimira-spilkova-michaela-pisova-standard-a-karierni-system-ucitele-problemy-predlozene-koncepce-v-sirsich-souvislostech/ unknown #166 - - http://ascestinaru.cz/ 30t
20170425094206/logs/crawl.log:2017-05-12T13:34:57.054Z     1         57 dns:journals.muni.cz LLLREXXP https://journals.muni.cz/pedor/article/view/2984 text/dns #089 20170512133457037+2 sha1:T6MWAJUMFPVONXL5WSGIQHUVUM55C2DD http://demagog.cz/ -
20170425094206/logs/crawl.log:2017-05-12T15:36:01.174Z    -2          0 https://journals.muni.cz/pedor/article/view/2984 LLLREXX http://dvorak-blog.eduin.cz/wp-json/wp/v2/posts unknown #034 - - http://demagog.cz/ 30t
20170425094206/logs/crawl.log:2017-05-12T19:38:04.831Z     1         57 dns:journals.muni.cz LLLREXXP https://journals.muni.cz/pedor/article/view/2729 text/dns #187 20170512193804813+3 sha1:KEERFWEFKB57WG6E3EYQM4OZHIZNAT2C http://demagog.cz/ -
20170425094206/logs/crawl.log:2017-05-12T22:39:44.575Z    -2          0 https://journals.muni.cz/pedor/article/view/2729 LLLREXX http://dvorak-blog.eduin.cz/wp-json/wp/v2/posts unknown #145 - - http://demagog.cz/ 30t
20170425094206/logs/crawl.log:2017-05-13T07:26:28.446Z  -404          0 https://journals.muni.cz/robots.txt LLLP https://journals.muni.cz/pedor/article/viewFile/1107/867 unknown #074 - - http://www.ceskaskola.cz/ -
20170425094206/logs/crawl.log:2017-05-13T07:41:28.720Z     1         57 dns:journals.muni.cz LLLP https://journals.muni.cz/pedor/article/viewFile/1107/867 text/dns #117 20170513074128717+2 sha1:U7ZG74P76Y6BEZG4RCJUIXYRELTCXZN7 http://www.ceskaskola.cz/ -
20170425094206/logs/crawl.log:2017-05-13T12:26:45.756Z    -2          0 https://journals.muni.cz/pedor/article/viewFile/1107/867 LLL http://www.ceskaskola.cz/2016/12/josef-koukal-ne-ucitelum-ale-tem.html unknown #034 - - http://www.ceskaskola.cz/ 30t
20170425094206/logs/crawl.log:2017-05-13T13:41:48.845Z     1         57 dns:journals.muni.cz LLLP https://journals.muni.cz/pedor/article/view/1140 text/dns #198 20170513134148841+3 sha1:NGFHOZ2LFXAHXS7C4K6DLW3DKJH5S2EN http://www.ceskaskola.cz/ -
20170425094206/logs/crawl.log:2017-05-13T19:26:59.232Z    -2          0 https://journals.muni.cz/pedor/article/view/1140 LLL http://www.ceskaskola.cz/2016/03/tomas-javorcik-vyuziti-osobniho.html unknown #155 - - http://www.ceskaskola.cz/ 30t
20170425094206/logs/crawl.log:2017-05-13T19:41:59.637Z     1         57 dns:journals.muni.cz LLLP https://journals.muni.cz/pedor/article/view/4383/pdf6 text/dns #027 20170513194159614+2 sha1:TM6IGWIFHDH3LXDT6GIOBYWWVAAZ2CLU http://www.ceskaskola.cz/ -
20170425094206/logs/crawl.log:2017-05-14T01:42:08.213Z     1         57 dns:journals.muni.cz LLLP https://journals.muni.cz/pedor/article/view/4383/pdf6 text/dns #162 20170514014208210+2 sha1:HHGZA4A3HVOK4GJ4LXN5IW7AMNLE7TJM http://www.ceskaskola.cz/ -
20170425094206/logs/crawl.log:2017-05-14T02:12:12.004Z    -2          0 https://journals.muni.cz/pedor/article/view/4383/pdf6 LLL http://www.ceskaskola.cz/2015/12/dag-hruby-ta-nase-maturita-ceska.html unknown #136 - - http://www.ceskaskola.cz/ 30t
20170425094206/logs/crawl.log:2017-05-14T07:27:17.613Z  -404          0 https://journals.muni.cz/robots.txt LLLLP https://journals.muni.cz/pedor/article/view/5233/pdf unknown #024 - - http://www.eduin.cz/ -
20170425094206/logs/crawl.log:2017-05-14T07:42:17.873Z     1         57 dns:journals.muni.cz LLLLP https://journals.muni.cz/pedor/article/view/5233/pdf text/dns #151 20170514074217870+2 sha1:5HTX2SETI3XXFZNRXFDEX6KE3AKIMO2Q http://www.eduin.cz/ -
20170425094206/logs/crawl.log:2017-05-14T08:57:23.205Z    -2          0 https://journals.muni.cz/pedor/article/view/5233/pdf LLLL http://www.eduin.cz/beduin/jak-je-mozne-ze-maturitni-katalogy-nekoresponduji-s-nekterymi-ramcovymi-vzdelavacimi-programy-pro-ss/ unknown #194 - - http://www.eduin.cz/ 30t
20170425094206/logs/crawl.log:2017-05-14T13:42:28.350Z     1         57 dns:journals.muni.cz LLLP https://journals.muni.cz/pedor/article/view/3676 text/dns #190 20170514134228334+3 sha1:6HL6C6MIXUTWKT77KIJGJLFHFGBIPTEC http://www.ceskaskola.cz/ -
20170425094206/logs/crawl.log:2017-05-14T15:57:34.039Z    -2          0 https://journals.muni.cz/pedor/article/view/3676 LLL http://www.ceskaskola.cz/2015/07/vladimir-spousta-anabaze-jednoho.html unknown #119 - - http://www.ceskaskola.cz/ 30t
20170425094206/logs/crawl.log:2017-05-15T01:42:48.233Z     1         57 dns:journals.muni.cz LLLRELP https://journals.muni.cz/pedor/article/view/2985 text/dns #016 20170515014248229+3 sha1:C4BILHXA55IYKFKMPNX6OXIWRQWDQPVM http://www.eduin.cz/ -
20170425094206/logs/crawl.log:2017-05-15T05:59:48.551Z    -2          0 https://journals.muni.cz/pedor/article/view/2985 LLLREL http://hrubanova-blog.eduin.cz/2016/08/25/a-jak-jste-se-meli-o-prazdninach-ne-to-fakt-neni-to-nejdulezitejsi-tema-na-zacatek-skolniho-roku/ unknown #101 - - http://www.eduin.cz/ 30t

**Comment by horakjirinkp** [comment]
Problém vyřešil přechodem na novější verzi crawleru.
