### ISSUE TITLE
safebryo - vir

### ISSUE THREAD

**Issue by ghost** [WebArchivCZ/Crawler-config#9]
Zdravím,
na webu safebryo (http://wayback.webarchiv.cz/secure/20090801000000*/http://www.safebryo.cz) je v roce 2009 a na některých dalších stránkách v pozdějších letech nějaký vir - dalo by s to prosím zrušit - smazat ty archivní verze s virem? 

plus jsou tam často místo klasického textu otazníky - víme/tušíme čím to je/může být? abychom třeba čtenářům řekli, co nedělat/dělat, aby tam místo textu neměli tyhle hlouposti kvůli kterým pak nejde přečíst text? 
Díky

**Comment by horakjirinkp** [comment]
Ne archivní verze smazat nelze, je to pracné.
Web již není na whitelistu. 

Níže uvedené weby které hlasí virovou nákazu vkládam do blacklistu, nebudou se zobrazovat.

https://wayback.webarchiv.cz/secure/20091023012852/http://safebryo.cz/
https://wayback.webarchiv.cz/secure/20091107220913/http://www.safebryo.cz/
https://wayback.webarchiv.cz/secure/20091201183612/http://www.safebryo.cz/

Problém uzavírám.
